### ISSUE TITLE
How to proceed after I have paid for the Developer plan

### ISSUE THREAD

**Issue by ebongfrank** [libreliodev/android#323]
After filling everything in the Librelio back-office platform and customizing the app I still have Wind appearing in my customized app.

**Comment by libreliodev** [comment]
Hi Frank,

In order to build your own app you have to select the "custom" target when building you app in Android Studio.
Before building with this target you need to create a file named "customer.gradle" in "main/src/script/"
In this file you have to specify the project.ext property like:
`project.ext {
    scriptApplicationId = "com.editor.appname"
}`
where you have to specify editor as your editor name and appname as your application name.

I hope this helps.

Best regards

**Comment by ebongfrank** [comment]
I will try and get back to you as soon as possible

Best Regards

Frank EBONG


On Mon, Jul 18, 2016 at 2:12 PM, Librelio Dev Team <notifications@github.com
