### ISSUE TITLE
How can I open the project in Android Studio?

### ISSUE THREAD

**Issue by zh-wowtv** [libreliodev/android#326]
How can I open the project in Android Studio? I got tons of errors when I import it to Android Studio? What should I do? Thanks.

**Comment by zh-wowtv** [comment]
What I did:

- Open Android Studio
- Import Projects

There could be a lot of errors. May need to install right SDK and setup the **target** and **compiled** version.

**Comment by GPDAJ** [comment]
Hello,
can you try to "Open project" and select the build.gradle file instead of selecting the "Import project" option ?
Also are you sure you used the build settings specified in the "building" part of the wiki ?
On my computer the project build correctly with this settings : 
-Gradle version: 2.14.1
-API 23
-Build Tools version: 23.0.2.
