### ISSUE TITLE
In zoom mode in PDF, when dragging , the text not displayed originally appears blur

### ISSUE THREAD

**Issue by deepiksdev** [libreliodev/android#42]
![2012-12-22 16 37 32](https://f.cloud.github.com/assets/2860170/28544/656054a4-4c4d-11e2-95a1-2969831bc2c4.png)

**Comment by shreyaj** [comment]
Hey, I integrated Mupdf Library into my application but on zooming in, the text is blurred and does not become clear ever. It is almost un readable. I have debugged my app code and the Mupdf project code to see where the issue is but I could not find anything different with both. The same file, when opened with the Mupdf project clears itself after a few seconds. Any help is appreciated. Thank you!

**Comment by libreliodev** [comment]
Sorry, this issue is not related to the Librelio app, is it?
